// Generated by Wrangler on Mon May 27 2024 19:43:23 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	semrushOAuthStore: KVNamespace;
	REDIRECT_URI: 'http://localhost:8787/redirect';
	AUTHORIZE_ENDPOINT: 'https://oauth.semrush.com/oauth2/authorize';
	TOKEN_ENDPOINT: 'https://oauth.semrush.com/oauth2/access_token';
	SCOPE: 'user.id';
	PLUGIN_URI: 'https://localhost:5174';
	CLIENT_ID: 'XXXXX';
	CLIENT_SECRET: 'XXXX';
}
